name: sse
description: A Example os shelf API using Server Sent Events
version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  eventsource: ^0.4.0
  shelf: ^1.3.0
  shelf_router: ^1.1.2

dev_dependencies:
  lints: ^1.0.0
